apiVersion: v1
kind: Pod
metadata:
  generateName: membomb-1-
  labels:
    app: membomb
spec:
  containers:
  - image: quay.io/appuio/membomb:latest
    imagePullPolicy: Always
    name: membomb
    env:
    - name: START_SIZE
      value: "-1"
    - name: SIZE_INCR
      value: "9"
  restartPolicy: Never
